# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Vercel Deploy (CI-triggered)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to Vercel
        run: |
          # Use Vercel CLI if configured via repository secrets (set VERCEL_TOKEN, etc.)
          npm i -g vercel@28 || true
          cd frontend
          # If VERCEL_TOKEN is not set this will fail; configure secrets in repo settings
          vercel --prod --confirm --token "$VERCEL_TOKEN" --org "$VERCEL_ORG_ID" --project "$VERCEL_PROJECT_ID"
